<template>
  <header>
    <span>Home</span>
    <span>|</span>
    <span>Jogadores</span>
    <span>|</span>
    <span>Times</span>
  </header>
  <main>times</main>
  <footer>rodapé</footer>
</template>